[verify]
package_hash = [
    { hash = "c8cd3b2f28d3fd84b73392f28ed196f807a3c667", name = "geth-hdwallet_<CLIENT_VERSION>-<CLIENT_REVISION>.dsc" },
    { hash = "8c29e3f8451ea63cd04f7ec40f861fe213897937", name = "geth-hdwallet_<CLIENT_VERSION>.orig.tar.gz" },
    { hash = "7e52d74af756ad00d774e11843b4132979972f0a", name = "geth-hdwallet_<CLIENT_VERSION>-<CLIENT_REVISION>.debian.tar.xz" },
    { hash = "dcd47b9850fae266ba3c410cd27eee5d7d4c1bb9", name = "geth-hdwallet_<CLIENT_VERSION>-<CLIENT_REVISION>_amd64.deb" },
]
