[package_fields]
spec_file = "eth-node-validator-regtest.sss"
package_name = "eth-node-validator-regtest"
version_number = "0.0.2"
revision_number = "1"
homepage="https://github.com/eth-pkg/eth-nodes"

[package_type]
package_type="virtual"

[build_env]
codename="noble numbat"
arch = "amd64"
pkg_builder_version="0.2.8"
debcrafter_version = "8189263"
run_lintian=true
run_piuparts=true
run_autopkgtest=false
lintian_version="2.116.3"
piuparts_version="1.1.7"
autopkgtest_version="5.28"
sbuild_version="0.85.6"
# package directory
workdir="~/.pkg-builder/packages/noble"