[verify]
package_hash = [
    # debian timestamps are again broken, this is a debian bug, this doesn't affect the package reproducibility
    # but would be a problem if we upload to official repository, which pkg-builder at this point can't support
    # { hash="70601da8e2bda3217c3e2d55792da08ffbe1ff5a", name= "eth-node-geth-regtest_0.0.2-1.dsc"},
    { hash = "b35f46d5fb424aee57b5d666e61b2eff83543aad", name = "eth-node-geth-regtest_0.0.2.orig.tar.gz" },
    # { hash="5d48d5fd702af111f108c095f86a56674b159e98", name= "eth-node-geth-regtest_0.0.2-1.debian.tar.xz"},
    { hash = "b8864b4fe8f8308143e0176451229c3d0f14d9a9", name = "eth-node-geth-regtest_0.0.2-1_all.deb" },
]
