[verify]
package_hash=[
    { hash="1affa0cf6d5798bd336f2ea9f4c0b9ee83b1a583", name= "eth-node-besu_24.7.1-1.dsc"},
    { hash="46f879bb7f2f9b869411b34902148764ded34987", name= "eth-node-besu_24.7.1.orig.tar.gz"},
    { hash="e0f2a11fd47cadab6472dc695228d37f5a09c8cc", name= "eth-node-besu_24.7.1-1.debian.tar.xz"},
    { hash="efd1253d5058f6c7027645073f1de0dc5b821dee", name= "eth-node-besu_24.7.1-1_amd64.deb"},
]
