[package_fields]
spec_file = "eth-node-lighthouse.sss"
package_name = "eth-node-lighthouse"
version_number = "4.5.0"
revision_number = "1"
homepage="https://github.com/sigp/lighthouse"

[package_type]
# virtual | git | default
package_type="default"
tarball_url = "https://github.com/sigp/lighthouse/archive/refs/tags/v4.5.0.tar.gz"
tarball_hash = ""
no_hash=true

[package_type.language_env]
language_env = "rust"
rust_version="1.77.2"
rust_binary_url="https://static.rust-lang.org/dist/rust-1.77.2-x86_64-unknown-linux-gnu.tar.xz"
rust_binary_gpg_asc="""
-----BEGIN PGP SIGNATURE-----

wsFcBAABCgAQBQJmFa+iCRCFq5bm+hvl/gAAc4oP/12rJYjE54yHsCgcpf6Lg+jz
h8HPP4uCET7gt7LZPBPaQPEllssvBE+OZPNXs2J/Bf9Dk+3Za2uEfSaEwRkuf2TV
EjLRkbxxjAx6e5FczAV0Qdd9u8O2LimndsRPOpjvIJtU4+wXnlHpPQ0lydr0rJso
/K9wdxvA3NgmNBa0SAKtGBwuziMk5tR+7gFFebJikXqnBsGgdifszL41tKSl5VkK
FUyb6xn0tA+wGmCVNiCV8JeTacr7+upJhAcMEqYWH/AuhA2vgF21W5jDPeA3VfoJ
RgPYUkbTKSdmUd68sUS5pzixxnYa6LXMBewshTim/kbxlMHxrZ+YSoOjBSuMUA/9
ZcvqR/fdVNLXI/2oFIT4VPNM1cYmR15xBI1G5AbfOzYWoPGU9OTu4hs11Y3DCTCz
E5obQCVAm4/H8gO3hTvDiJE0Rb2M0h1uV12LkCMymzuIBrhLkVhQeekDZadJmWq0
XlT/N86YFd8P393xYE3fpKaGqZ0fBJfX4nLdZHdZeFrov6ADjf7NLsfY0S9AnRnK
SAytDb5EQMcBZXlNKnF+mLG9l0Y4JtijEsaiMaJgzVInTIUTtkW/GlgpAgzIBQ8m
KGFMBQELjcFWLGcBVE45DRuVR8E3XYunjSdgLFXjfZfeGF3uiS6fNHGCH41ryqfj
2jwoU0cewz4tgDucAWWC
=sCT4
-----END PGP SIGNATURE-----
"""

[build_env]
codename="bookworm"
arch = "amd64"
# TODO not used yet
pkg_builder_version="0.1"
# TODO not used yet
debcrafter_version = "latest"
run_lintian=false
run_piuparts=false
run_autopkgtest=false
# package directory
workdir="~/.pkg-builder/packages"

[cli_options]
# not used
is_ci=false
log="info"
log_to="file"
reuse_previous_build=false

[verify]
# if tarball_url is specified
tarball_hash=""
# if git_source is specified and package_is_git
git_commit=""
# output hash
bin_bash=""